version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"  # For the "backend" subdirectory
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/frontend"  # For the "frontend" subdirectory
    schedule:
      interval: "daily"
