version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"  # Root of the repository
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"  # For the "frontend" subdirectory
    schedule:
      interval: "daily"
